still fighting yml issues

diff --git a/.github/workflows/_deploy-sites.yml b/.github/workflows/_deploy-sites.yml
--- a/.github/workflows/_deploy-sites.yml
+++ b/.github/workflows/_deploy-sites.yml
@@ -59,15 +59,15 @@ jobs:
         run: |
           export CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }}
           export CLOUDFLARE_ACCOUNT_ID=6a22f9b8ad27ffcc9719dd53a78bcedf
-          wrangler pages deploy ${{ inputs.siteDirectory }}/dist --project-name=${{ inputs.projectName }} --commit-dirty=true
+          wrangler pages deploy ${{ inputs.workingDirectory }}/dist --project-name=${{ inputs.projectName }} --commit-dirty=true
 
       - name: Dump site directory (on failure)
         if: failure()
         run: |
-          echo "Contents of ${{ inputs.siteDirectory }}:"
+          echo "Contents of ${{ inputs.workingDirectory }}:"
           ls -la ${{ inputs.siteDirectory }}
           echo "--- index.html ---"
-          cat ${{ inputs.siteDirectory }}/index.html || echo "Missing index.html"
+          cat ${{ inputs.workingDirectory }}/index.html || echo "Missing index.html"
 
       - name: Output Wrangler error log (on failure)
         if: failure()
